/**
 * Demo reset.
 *
 * `demo_baseline` holds a JSON snapshot of every seeded demo row (accounts,
 * pots, cards, merchants, loyalty accounts). Resetting writes those values
 * back and clears the churn produced by demo activity, so the sandbox is
 * repeatable for sales demos and end-to-end tests.
 */
import { timingSafeEqual } from "crypto";

export function checkJobsSecret(request: Request): boolean {
  const expected =
    process.env["ZORYN_JOBS_SECRET"] ??
    process.env["SUPABASE_ANON_KEY"] ??
    process.env["SUPABASE_PUBLISHABLE_KEY"];
  if (!expected) return false;
  const provided = request.headers.get("x-zoryn-jobs-secret") ?? request.headers.get("apikey") ?? "";
  const a = Buffer.from(provided);
  const b = Buffer.from(expected);
  return a.length === b.length && timingSafeEqual(a, b);
}

const BASELINE_TABLES = ["financial_accounts", "pots", "cards", "merchants", "loyalty_accounts"] as const;

export async function resetDemoData(admin: any) {
  const restored: Record<string, number> = {};
  const cleared: Record<string, number> = {};

  // 1. Clear activity generated by demo usage.
  for (const table of [
    "internal_transfers",
    "loyalty_entries",
    "payment_links",
    "transactions",
    "rewards_outbox",
    "provider_events",
    "audit_logs",
    "support_cases",
  ]) {
    const { data } = await admin
      .from(table)
      .delete()
      .eq(table === "internal_transfers" ? "id" : "is_demo", table === "internal_transfers" ? undefined : true)
      .not("id", "is", null)
      .select("id");
    cleared[table] = data?.length ?? 0;
  }

  // 2. Restore the seeded snapshot.
  const { data: baseline } = await admin.from("demo_baseline").select("table_name, row_id, data");
  for (const table of BASELINE_TABLES) {
    const rows = (baseline ?? []).filter((r: any) => r.table_name === table);
    for (const row of rows) {
      await admin.from(table).upsert({ ...(row.data as Record<string, unknown>), id: row.row_id });
    }
    restored[table] = rows.length;
  }

  return { ok: true, restored, cleared };
}
