from abc import ABC, abstractmethod

class BankingProvider(ABC):
    @abstractmethod
    async def create_customer(self, payload: dict) -> dict: ...
    @abstractmethod
    async def open_account(self, customer_id: str) -> dict: ...
    @abstractmethod
    async def create_transfer(self, payload: dict) -> dict: ...

class AcquiringProvider(ABC):
    @abstractmethod
    async def create_merchant(self, payload: dict) -> dict: ...
    @abstractmethod
    async def create_payment_link(self, payload: dict) -> dict: ...
