import { useMemo, useState } from "react";
import { Activity, Building2, CreditCard, Landmark, ShieldCheck, WalletCards } from "lucide-react";
import { demoAccounts, demoCards, demoCustomer, demoMerchant, demoPots, demoTeam, demoTransactions, providerHealth, scenarios, webhookEvents } from "../data/scenarios";
import { eur, dateTime } from "../lib/format";
import { MetricCard } from "./MetricCard";
import { StatusBadge } from "./StatusBadge";

type Tab = "overview" | "personal" | "business" | "pay" | "operations" | "scenarios";
export function ProviderReadyCentre() {
 const [tab,setTab]=useState<Tab>("overview");
 const [pots,setPots]=useState(demoPots);
 const [mainBalance,setMainBalance]=useState(demoAccounts[0].availableCents);
 const [amount,setAmount]=useState("100");
 const [selectedPot,setSelectedPot]=useState(demoPots[0].id);
 const activePot=useMemo(()=>pots.find(p=>p.id===selectedPot)!,[pots,selectedPot]);
 const moveToPot=()=>{ const cents=Math.round(Number(amount)*100); if(!Number.isFinite(cents)||cents<=0||cents>mainBalance)return; setMainBalance(v=>v-cents); setPots(p=>p.map(x=>x.id===selectedPot?{...x,balanceCents:x.balanceCents+cents}:x)); };
 const moveFromPot=()=>{ const cents=Math.round(Number(amount)*100); if(!Number.isFinite(cents)||cents<=0||cents>activePot.balanceCents)return; setMainBalance(v=>v+cents); setPots(p=>p.map(x=>x.id===selectedPot?{...x,balanceCents:x.balanceCents-cents}:x)); };
 const tabs: {id:Tab;label:string}[]=[{id:"overview",label:"Overview"},{id:"personal",label:"Personal"},{id:"business",label:"Business"},{id:"pay",label:"ZorynPay"},{id:"operations",label:"Operations"},{id:"scenarios",label:"Scenario Lab"}];
 return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="border-b border-slate-200 bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.22em] text-emerald-300">Zoryn Nexus</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Provider-ready product centre</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Production-state UX, realistic banking, business, acquiring, rewards and operations scenarios prepared for Swan and Adyen adapters.</p></div><div className="flex flex-wrap gap-2">{tabs.map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`rounded-full px-4 py-2 text-sm font-semibold transition ${tab===x.id?"bg-white text-slate-950":"bg-white/10 text-white hover:bg-white/20"}`}>{x.label}</button>)}</div></div></div></header><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
 {tab==="overview"&&<div className="space-y-8"><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Available balance" value={eur(mainBalance)} help={demoAccounts[0].iban} icon={<Landmark className="text-emerald-600"/>}/><MetricCard label="Rewards value" value="€42.80" help="4,280 points + €7.30 cashback" icon={<WalletCards className="text-violet-600"/>}/><MetricCard label="Today's merchant sales" value={eur(demoMerchant.todaySalesCents)} help={`${demoMerchant.terminalsOnline}/${demoMerchant.terminalsTotal} terminals online`} icon={<CreditCard className="text-blue-600"/>}/><MetricCard label="Open review actions" value="7" help="2 high priority" icon={<ShieldCheck className="text-amber-600"/>}/></section><section className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Account readiness</h2><p className="text-sm text-slate-500">Customer and provider state mapping</p></div><StatusBadge status={demoCustomer.status}/></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Account holder</p><p className="mt-2 font-semibold">{demoCustomer.name}</p><p className="text-sm text-slate-500">Risk score {demoCustomer.riskScore}/100</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Regulated source</p><p className="mt-2 font-semibold">Swan adapter</p><p className="text-sm text-slate-500">Mock mode until sandbox keys are added</p></div></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Provider health</h2><div className="mt-4 space-y-3">{providerHealth.map(p=><div key={p.provider} className="flex items-start justify-between gap-3 rounded-2xl bg-slate-50 p-3"><div><p className="font-semibold capitalize">{p.provider}</p><p className="text-xs text-slate-500">{p.message}</p></div><StatusBadge status={p.status}/></div>)}</div></div></section></div>}
 {tab==="personal"&&<div className="space-y-8"><section className="grid gap-4 lg:grid-cols-3"><MetricCard label="Main account" value={eur(mainBalance)} help={demoAccounts[0].iban}/><MetricCard label="Pots" value={eur(pots.reduce((a,p)=>a+p.balanceCents,0))} help={`${pots.length} savings goals`}/><MetricCard label="Cards" value={`${demoCards.filter(c=>c.status==="active").length} active`} help={`${demoCards.length} total`}/></section><section className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Move money between account and pots</h2><label className="mt-5 block text-sm font-semibold">Savings pot<select value={selectedPot} onChange={e=>setSelectedPot(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3">{pots.map(p=><option key={p.id} value={p.id}>{p.name} · {eur(p.balanceCents)}</option>)}</select></label><label className="mt-4 block text-sm font-semibold">Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" className="mt-2 w-full rounded-xl border border-slate-300 px-3 py-3"/></label><div className="mt-4 grid grid-cols-2 gap-3"><button onClick={moveToPot} className="rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white">Move to pot</button><button onClick={moveFromPot} className="rounded-xl border border-slate-300 px-4 py-3 text-sm font-bold">Move to main</button></div><p className="mt-3 text-xs text-slate-500">Mock allocations persist for this session. In production Swan remains the ledger source of truth.</p></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Recent transactions</h2><div className="mt-4 divide-y divide-slate-100">{demoTransactions.map(tx=><div key={tx.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{tx.counterparty}</p><p className="text-xs text-slate-500">{tx.category} · {dateTime(tx.bookedAt)} · {tx.reference}</p>{tx.rewardsPoints!=null&&<p className="mt-1 text-xs font-medium text-violet-700">{tx.rewardsPoints>0?"+":""}{tx.rewardsPoints} reward points</p>}</div><div className="text-right"><p className={`font-bold ${tx.amountCents<0?"text-slate-950":"text-emerald-700"}`}>{eur(tx.amountCents)}</p><StatusBadge status={tx.status}/></div></div>)}</div></div></section><section className="grid gap-4 md:grid-cols-3">{demoCards.map(c=><div key={c.id} className="rounded-3xl bg-gradient-to-br from-slate-950 to-slate-700 p-5 text-white shadow-lg"><div className="flex justify-between"><p className="font-semibold">{c.label}</p><StatusBadge status={c.status}/></div><p className="mt-10 text-xl tracking-[.25em]">•••• {c.last4}</p><p className="mt-4 text-xs text-slate-300">Spent {eur(c.spentCents)} of {eur(c.monthlyLimitCents)}</p></div>)}</section></div>}
 {tab==="business"&&<div className="space-y-8"><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Operating balance" value="€64,280.20" help="Active GmbH account"/><MetricCard label="Pending approvals" value="€8,400.00" help="1 supplier payment"/><MetricCard label="Card spend" value="€12,680.40" help="Across 8 active staff cards"/><MetricCard label="Missing receipts" value="6" help="2 overdue"/></section><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Building2 className="text-blue-600"/><h2 className="text-xl font-bold">Team and permissions</h2></div><div className="mt-4 space-y-3">{demoTeam.map(m=><div key={m.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="font-semibold">{m.name}</p><p className="text-xs capitalize text-slate-500">{m.role} · approval limit {eur(m.approvalLimitCents)}</p></div><StatusBadge status={m.status}/></div>)}</div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Business actions</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{["Create supplier transfer","Invite team member","Issue staff card","Upload receipt","Export DATEV data","Create approval policy"].map(x=><button key={x} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 text-left text-sm font-semibold hover:bg-slate-100">{x}</button>)}</div></div></section></div>}
 {tab==="pay"&&<div className="space-y-8"><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Today's sales" value={eur(demoMerchant.todaySalesCents)} help="124 payments"/><MetricCard label="Pending settlement" value={eur(demoMerchant.pendingSettlementCents)} help="Expected tomorrow"/><MetricCard label="Refunds" value="€184.50" help="3 partial, 1 full"/><MetricCard label="Reward redemptions" value="€96.00" help="24 customers"/></section><section className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Tap to Pay readiness</h2><div className="mt-5 rounded-[2rem] bg-slate-950 p-6 text-white"><p className="text-sm text-slate-300">ZorynPay · Cafe Berlin Mitte</p><p className="mt-8 text-center text-5xl font-bold">€24.90</p><div className="mx-auto mt-8 flex h-32 w-32 items-center justify-center rounded-full border-4 border-emerald-400/50 bg-emerald-400/10"><Activity className="h-14 w-14 text-emerald-300"/></div><p className="mt-5 text-center font-semibold">Ready for customer tap</p><p className="mt-1 text-center text-xs text-slate-400">Adyen Mobile SDK replaces this simulation.</p></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Terminal estate</h2><div className="mt-4 space-y-3">{[{n:"Mitte counter",s:"online",b:"82%"},{n:"Mitte mobile",s:"online",b:"61%"},{n:"Kitchen terminal",s:"offline",b:"14%"}].map(x=><div key={x.n} className="flex items-center justify-between rounded-2xl bg-slate-50 p-4"><div><p className="font-semibold">{x.n}</p><p className="text-xs text-slate-500">Battery {x.b}</p></div><StatusBadge status={x.s}/></div>)}</div></div></section></div>}
 {tab==="operations"&&<div className="space-y-8"><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><ShieldCheck className="text-emerald-600"/><div><h2 className="text-xl font-bold">Webhook event centre</h2><p className="text-sm text-slate-500">Idempotency, retries, ordering and dead-letter visibility.</p></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><th className="py-3">Provider</th><th>Event</th><th>Resource</th><th>Occurred</th><th>Attempts</th><th>Status</th></tr></thead><tbody>{webhookEvents.map(e=><tr key={e.id} className="border-b border-slate-100"><td className="py-4 capitalize">{e.provider}</td><td className="font-medium">{e.type}</td><td>{e.resourceId}</td><td>{dateTime(e.occurredAt)}</td><td>{e.attempts}</td><td><StatusBadge status={e.status}/>{e.error&&<p className="mt-1 max-w-xs text-xs text-red-600">{e.error}</p>}</td></tr>)}</tbody></table></div></section></div>}
 {tab==="scenarios"&&<div className="space-y-6"><div><h2 className="text-2xl font-bold">Realistic scenario lab</h2><p className="mt-1 text-sm text-slate-500">Successful, failed, restricted and asynchronous journeys for demos and acceptance testing.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{scenarios.map(s=><div key={s.id} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wide text-slate-500">{s.group}</span><StatusBadge status={s.severity}/></div><h3 className="mt-4 text-lg font-bold">{s.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{s.description}</p><div className="mt-4"><StatusBadge status={s.status}/></div></div>)}</div></div>}
 </div></main>
}
