/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OnboardingStatusRouteImport } from './routes/onboarding-status'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as OperationsCentreRouteImport } from './routes/operations-centre'
import { Route as ProductionReadyRouteImport } from './routes/production-ready'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProviderReadyRouteImport } from './routes/provider-ready'
import { Route as ScenarioLabRouteImport } from './routes/scenario-lab'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBusinessRouteImport } from './routes/_authenticated/business'
import { Route as AuthenticatedBusinessWorkspaceRouteImport } from './routes/_authenticated/business-workspace'
import { Route as AuthenticatedControlRoomRouteImport } from './routes/_authenticated/control-room'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedPersonalRouteImport } from './routes/_authenticated/personal'
import { Route as AuthenticatedPersonalWorkspaceRouteImport } from './routes/_authenticated/personal-workspace'
import { Route as AuthenticatedProviderIntegrationRouteImport } from './routes/_authenticated/provider-integration'
import { Route as AuthenticatedZorynpayWorkspaceRouteImport } from './routes/_authenticated/zorynpay-workspace'
import { Route as ApiPublicDemoResetRouteImport } from './routes/api/public/demo-reset'
import { Route as ApiPublicNotificationWorkerRouteImport } from './routes/api/public/notification-worker'
import { Route as ApiPublicPlatformProviderWebhooksRouteImport } from './routes/api/public/platform-provider-webhooks'
import { Route as ApiPublicProviderApiRouteImport } from './routes/api/public/provider-api'
import { Route as ApiPublicProviderCommandWorkerRouteImport } from './routes/api/public/provider-command-worker'
import { Route as ApiPublicProviderEventProcessorRouteImport } from './routes/api/public/provider-event-processor'
import { Route as ApiPublicProviderHealthRouteImport } from './routes/api/public/provider-health'
import { Route as ApiPublicProviderJobsRouteImport } from './routes/api/public/provider-jobs'
import { Route as ApiPublicProviderWebhooksRouteImport } from './routes/api/public/provider-webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStatusRoute = OnboardingStatusRouteImport.update({
  id: '/onboarding-status',
  path: '/onboarding-status',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsCentreRoute = OperationsCentreRouteImport.update({
  id: '/operations-centre',
  path: '/operations-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionReadyRoute = ProductionReadyRouteImport.update({
  id: '/production-ready',
  path: '/production-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderReadyRoute = ProviderReadyRouteImport.update({
  id: '/provider-ready',
  path: '/provider-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioLabRoute = ScenarioLabRouteImport.update({
  id: '/scenario-lab',
  path: '/scenario-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRoute = AuthenticatedBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessWorkspaceRoute =
  AuthenticatedBusinessWorkspaceRouteImport.update({
    id: '/business-workspace',
    path: '/business-workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedControlRoomRoute =
  AuthenticatedControlRoomRouteImport.update({
    id: '/control-room',
    path: '/control-room',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalRoute = AuthenticatedPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalWorkspaceRoute =
  AuthenticatedPersonalWorkspaceRouteImport.update({
    id: '/personal-workspace',
    path: '/personal-workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderIntegrationRoute =
  AuthenticatedProviderIntegrationRouteImport.update({
    id: '/provider-integration',
    path: '/provider-integration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZorynpayWorkspaceRoute =
  AuthenticatedZorynpayWorkspaceRouteImport.update({
    id: '/zorynpay-workspace',
    path: '/zorynpay-workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicDemoResetRoute = ApiPublicDemoResetRouteImport.update({
  id: '/api/public/demo-reset',
  path: '/api/public/demo-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotificationWorkerRoute =
  ApiPublicNotificationWorkerRouteImport.update({
    id: '/api/public/notification-worker',
    path: '/api/public/notification-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPlatformProviderWebhooksRoute =
  ApiPublicPlatformProviderWebhooksRouteImport.update({
    id: '/api/public/platform-provider-webhooks',
    path: '/api/public/platform-provider-webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProviderApiRoute = ApiPublicProviderApiRouteImport.update({
  id: '/api/public/provider-api',
  path: '/api/public/provider-api',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProviderCommandWorkerRoute =
  ApiPublicProviderCommandWorkerRouteImport.update({
    id: '/api/public/provider-command-worker',
    path: '/api/public/provider-command-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProviderEventProcessorRoute =
  ApiPublicProviderEventProcessorRouteImport.update({
    id: '/api/public/provider-event-processor',
    path: '/api/public/provider-event-processor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProviderHealthRoute = ApiPublicProviderHealthRouteImport.update({
  id: '/api/public/provider-health',
  path: '/api/public/provider-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProviderJobsRoute = ApiPublicProviderJobsRouteImport.update({
  id: '/api/public/provider-jobs',
  path: '/api/public/provider-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProviderWebhooksRoute =
  ApiPublicProviderWebhooksRouteImport.update({
    id: '/api/public/provider-webhooks',
    path: '/api/public/provider-webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-status': typeof OnboardingStatusRoute
  '/operations': typeof OperationsRoute
  '/operations-centre': typeof OperationsCentreRoute
  '/production-ready': typeof ProductionReadyRoute
  '/products': typeof ProductsRoute
  '/provider-ready': typeof ProviderReadyRoute
  '/scenario-lab': typeof ScenarioLabRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/business-workspace': typeof AuthenticatedBusinessWorkspaceRoute
  '/control-room': typeof AuthenticatedControlRoomRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/personal': typeof AuthenticatedPersonalRoute
  '/personal-workspace': typeof AuthenticatedPersonalWorkspaceRoute
  '/provider-integration': typeof AuthenticatedProviderIntegrationRoute
  '/zorynpay-workspace': typeof AuthenticatedZorynpayWorkspaceRoute
  '/api/public/demo-reset': typeof ApiPublicDemoResetRoute
  '/api/public/notification-worker': typeof ApiPublicNotificationWorkerRoute
  '/api/public/platform-provider-webhooks': typeof ApiPublicPlatformProviderWebhooksRoute
  '/api/public/provider-api': typeof ApiPublicProviderApiRoute
  '/api/public/provider-command-worker': typeof ApiPublicProviderCommandWorkerRoute
  '/api/public/provider-event-processor': typeof ApiPublicProviderEventProcessorRoute
  '/api/public/provider-health': typeof ApiPublicProviderHealthRoute
  '/api/public/provider-jobs': typeof ApiPublicProviderJobsRoute
  '/api/public/provider-webhooks': typeof ApiPublicProviderWebhooksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-status': typeof OnboardingStatusRoute
  '/operations': typeof OperationsRoute
  '/operations-centre': typeof OperationsCentreRoute
  '/production-ready': typeof ProductionReadyRoute
  '/products': typeof ProductsRoute
  '/provider-ready': typeof ProviderReadyRoute
  '/scenario-lab': typeof ScenarioLabRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/business': typeof AuthenticatedBusinessRoute
  '/business-workspace': typeof AuthenticatedBusinessWorkspaceRoute
  '/control-room': typeof AuthenticatedControlRoomRoute
  '/merchant': typeof AuthenticatedMerchantRoute
  '/personal': typeof AuthenticatedPersonalRoute
  '/personal-workspace': typeof AuthenticatedPersonalWorkspaceRoute
  '/provider-integration': typeof AuthenticatedProviderIntegrationRoute
  '/zorynpay-workspace': typeof AuthenticatedZorynpayWorkspaceRoute
  '/api/public/demo-reset': typeof ApiPublicDemoResetRoute
  '/api/public/notification-worker': typeof ApiPublicNotificationWorkerRoute
  '/api/public/platform-provider-webhooks': typeof ApiPublicPlatformProviderWebhooksRoute
  '/api/public/provider-api': typeof ApiPublicProviderApiRoute
  '/api/public/provider-command-worker': typeof ApiPublicProviderCommandWorkerRoute
  '/api/public/provider-event-processor': typeof ApiPublicProviderEventProcessorRoute
  '/api/public/provider-health': typeof ApiPublicProviderHealthRoute
  '/api/public/provider-jobs': typeof ApiPublicProviderJobsRoute
  '/api/public/provider-webhooks': typeof ApiPublicProviderWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-status': typeof OnboardingStatusRoute
  '/operations': typeof OperationsRoute
  '/operations-centre': typeof OperationsCentreRoute
  '/production-ready': typeof ProductionReadyRoute
  '/products': typeof ProductsRoute
  '/provider-ready': typeof ProviderReadyRoute
  '/scenario-lab': typeof ScenarioLabRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/business': typeof AuthenticatedBusinessRoute
  '/_authenticated/business-workspace': typeof AuthenticatedBusinessWorkspaceRoute
  '/_authenticated/control-room': typeof AuthenticatedControlRoomRoute
  '/_authenticated/merchant': typeof AuthenticatedMerchantRoute
  '/_authenticated/personal': typeof AuthenticatedPersonalRoute
  '/_authenticated/personal-workspace': typeof AuthenticatedPersonalWorkspaceRoute
  '/_authenticated/provider-integration': typeof AuthenticatedProviderIntegrationRoute
  '/_authenticated/zorynpay-workspace': typeof AuthenticatedZorynpayWorkspaceRoute
  '/api/public/demo-reset': typeof ApiPublicDemoResetRoute
  '/api/public/notification-worker': typeof ApiPublicNotificationWorkerRoute
  '/api/public/platform-provider-webhooks': typeof ApiPublicPlatformProviderWebhooksRoute
  '/api/public/provider-api': typeof ApiPublicProviderApiRoute
  '/api/public/provider-command-worker': typeof ApiPublicProviderCommandWorkerRoute
  '/api/public/provider-event-processor': typeof ApiPublicProviderEventProcessorRoute
  '/api/public/provider-health': typeof ApiPublicProviderHealthRoute
  '/api/public/provider-jobs': typeof ApiPublicProviderJobsRoute
  '/api/public/provider-webhooks': typeof ApiPublicProviderWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/onboarding'
    | '/onboarding-status'
    | '/operations'
    | '/operations-centre'
    | '/production-ready'
    | '/products'
    | '/provider-ready'
    | '/scenario-lab'
    | '/admin'
    | '/business'
    | '/business-workspace'
    | '/control-room'
    | '/merchant'
    | '/personal'
    | '/personal-workspace'
    | '/provider-integration'
    | '/zorynpay-workspace'
    | '/api/public/demo-reset'
    | '/api/public/notification-worker'
    | '/api/public/platform-provider-webhooks'
    | '/api/public/provider-api'
    | '/api/public/provider-command-worker'
    | '/api/public/provider-event-processor'
    | '/api/public/provider-health'
    | '/api/public/provider-jobs'
    | '/api/public/provider-webhooks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/onboarding'
    | '/onboarding-status'
    | '/operations'
    | '/operations-centre'
    | '/production-ready'
    | '/products'
    | '/provider-ready'
    | '/scenario-lab'
    | '/admin'
    | '/business'
    | '/business-workspace'
    | '/control-room'
    | '/merchant'
    | '/personal'
    | '/personal-workspace'
    | '/provider-integration'
    | '/zorynpay-workspace'
    | '/api/public/demo-reset'
    | '/api/public/notification-worker'
    | '/api/public/platform-provider-webhooks'
    | '/api/public/provider-api'
    | '/api/public/provider-command-worker'
    | '/api/public/provider-event-processor'
    | '/api/public/provider-health'
    | '/api/public/provider-jobs'
    | '/api/public/provider-webhooks'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/onboarding'
    | '/onboarding-status'
    | '/operations'
    | '/operations-centre'
    | '/production-ready'
    | '/products'
    | '/provider-ready'
    | '/scenario-lab'
    | '/_authenticated/admin'
    | '/_authenticated/business'
    | '/_authenticated/business-workspace'
    | '/_authenticated/control-room'
    | '/_authenticated/merchant'
    | '/_authenticated/personal'
    | '/_authenticated/personal-workspace'
    | '/_authenticated/provider-integration'
    | '/_authenticated/zorynpay-workspace'
    | '/api/public/demo-reset'
    | '/api/public/notification-worker'
    | '/api/public/platform-provider-webhooks'
    | '/api/public/provider-api'
    | '/api/public/provider-command-worker'
    | '/api/public/provider-event-processor'
    | '/api/public/provider-health'
    | '/api/public/provider-jobs'
    | '/api/public/provider-webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingStatusRoute: typeof OnboardingStatusRoute
  OperationsRoute: typeof OperationsRoute
  OperationsCentreRoute: typeof OperationsCentreRoute
  ProductionReadyRoute: typeof ProductionReadyRoute
  ProductsRoute: typeof ProductsRoute
  ProviderReadyRoute: typeof ProviderReadyRoute
  ScenarioLabRoute: typeof ScenarioLabRoute
  ApiPublicDemoResetRoute: typeof ApiPublicDemoResetRoute
  ApiPublicNotificationWorkerRoute: typeof ApiPublicNotificationWorkerRoute
  ApiPublicPlatformProviderWebhooksRoute: typeof ApiPublicPlatformProviderWebhooksRoute
  ApiPublicProviderApiRoute: typeof ApiPublicProviderApiRoute
  ApiPublicProviderCommandWorkerRoute: typeof ApiPublicProviderCommandWorkerRoute
  ApiPublicProviderEventProcessorRoute: typeof ApiPublicProviderEventProcessorRoute
  ApiPublicProviderHealthRoute: typeof ApiPublicProviderHealthRoute
  ApiPublicProviderJobsRoute: typeof ApiPublicProviderJobsRoute
  ApiPublicProviderWebhooksRoute: typeof ApiPublicProviderWebhooksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-status': {
      id: '/onboarding-status'
      path: '/onboarding-status'
      fullPath: '/onboarding-status'
      preLoaderRoute: typeof OnboardingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations-centre': {
      id: '/operations-centre'
      path: '/operations-centre'
      fullPath: '/operations-centre'
      preLoaderRoute: typeof OperationsCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production-ready': {
      id: '/production-ready'
      path: '/production-ready'
      fullPath: '/production-ready'
      preLoaderRoute: typeof ProductionReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-ready': {
      id: '/provider-ready'
      path: '/provider-ready'
      fullPath: '/provider-ready'
      preLoaderRoute: typeof ProviderReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-lab': {
      id: '/scenario-lab'
      path: '/scenario-lab'
      fullPath: '/scenario-lab'
      preLoaderRoute: typeof ScenarioLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business-workspace': {
      id: '/_authenticated/business-workspace'
      path: '/business-workspace'
      fullPath: '/business-workspace'
      preLoaderRoute: typeof AuthenticatedBusinessWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/control-room': {
      id: '/_authenticated/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof AuthenticatedControlRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal': {
      id: '/_authenticated/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof AuthenticatedPersonalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal-workspace': {
      id: '/_authenticated/personal-workspace'
      path: '/personal-workspace'
      fullPath: '/personal-workspace'
      preLoaderRoute: typeof AuthenticatedPersonalWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider-integration': {
      id: '/_authenticated/provider-integration'
      path: '/provider-integration'
      fullPath: '/provider-integration'
      preLoaderRoute: typeof AuthenticatedProviderIntegrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zorynpay-workspace': {
      id: '/_authenticated/zorynpay-workspace'
      path: '/zorynpay-workspace'
      fullPath: '/zorynpay-workspace'
      preLoaderRoute: typeof AuthenticatedZorynpayWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/demo-reset': {
      id: '/api/public/demo-reset'
      path: '/api/public/demo-reset'
      fullPath: '/api/public/demo-reset'
      preLoaderRoute: typeof ApiPublicDemoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notification-worker': {
      id: '/api/public/notification-worker'
      path: '/api/public/notification-worker'
      fullPath: '/api/public/notification-worker'
      preLoaderRoute: typeof ApiPublicNotificationWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/platform-provider-webhooks': {
      id: '/api/public/platform-provider-webhooks'
      path: '/api/public/platform-provider-webhooks'
      fullPath: '/api/public/platform-provider-webhooks'
      preLoaderRoute: typeof ApiPublicPlatformProviderWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-api': {
      id: '/api/public/provider-api'
      path: '/api/public/provider-api'
      fullPath: '/api/public/provider-api'
      preLoaderRoute: typeof ApiPublicProviderApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-command-worker': {
      id: '/api/public/provider-command-worker'
      path: '/api/public/provider-command-worker'
      fullPath: '/api/public/provider-command-worker'
      preLoaderRoute: typeof ApiPublicProviderCommandWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-event-processor': {
      id: '/api/public/provider-event-processor'
      path: '/api/public/provider-event-processor'
      fullPath: '/api/public/provider-event-processor'
      preLoaderRoute: typeof ApiPublicProviderEventProcessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-health': {
      id: '/api/public/provider-health'
      path: '/api/public/provider-health'
      fullPath: '/api/public/provider-health'
      preLoaderRoute: typeof ApiPublicProviderHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-jobs': {
      id: '/api/public/provider-jobs'
      path: '/api/public/provider-jobs'
      fullPath: '/api/public/provider-jobs'
      preLoaderRoute: typeof ApiPublicProviderJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/provider-webhooks': {
      id: '/api/public/provider-webhooks'
      path: '/api/public/provider-webhooks'
      fullPath: '/api/public/provider-webhooks'
      preLoaderRoute: typeof ApiPublicProviderWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBusinessRoute: typeof AuthenticatedBusinessRoute
  AuthenticatedBusinessWorkspaceRoute: typeof AuthenticatedBusinessWorkspaceRoute
  AuthenticatedControlRoomRoute: typeof AuthenticatedControlRoomRoute
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRoute
  AuthenticatedPersonalRoute: typeof AuthenticatedPersonalRoute
  AuthenticatedPersonalWorkspaceRoute: typeof AuthenticatedPersonalWorkspaceRoute
  AuthenticatedProviderIntegrationRoute: typeof AuthenticatedProviderIntegrationRoute
  AuthenticatedZorynpayWorkspaceRoute: typeof AuthenticatedZorynpayWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBusinessRoute: AuthenticatedBusinessRoute,
  AuthenticatedBusinessWorkspaceRoute: AuthenticatedBusinessWorkspaceRoute,
  AuthenticatedControlRoomRoute: AuthenticatedControlRoomRoute,
  AuthenticatedMerchantRoute: AuthenticatedMerchantRoute,
  AuthenticatedPersonalRoute: AuthenticatedPersonalRoute,
  AuthenticatedPersonalWorkspaceRoute: AuthenticatedPersonalWorkspaceRoute,
  AuthenticatedProviderIntegrationRoute: AuthenticatedProviderIntegrationRoute,
  AuthenticatedZorynpayWorkspaceRoute: AuthenticatedZorynpayWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingStatusRoute: OnboardingStatusRoute,
  OperationsRoute: OperationsRoute,
  OperationsCentreRoute: OperationsCentreRoute,
  ProductionReadyRoute: ProductionReadyRoute,
  ProductsRoute: ProductsRoute,
  ProviderReadyRoute: ProviderReadyRoute,
  ScenarioLabRoute: ScenarioLabRoute,
  ApiPublicDemoResetRoute: ApiPublicDemoResetRoute,
  ApiPublicNotificationWorkerRoute: ApiPublicNotificationWorkerRoute,
  ApiPublicPlatformProviderWebhooksRoute:
    ApiPublicPlatformProviderWebhooksRoute,
  ApiPublicProviderApiRoute: ApiPublicProviderApiRoute,
  ApiPublicProviderCommandWorkerRoute: ApiPublicProviderCommandWorkerRoute,
  ApiPublicProviderEventProcessorRoute: ApiPublicProviderEventProcessorRoute,
  ApiPublicProviderHealthRoute: ApiPublicProviderHealthRoute,
  ApiPublicProviderJobsRoute: ApiPublicProviderJobsRoute,
  ApiPublicProviderWebhooksRoute: ApiPublicProviderWebhooksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
