/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as OnboardingStatusRouteImport } from './routes/onboarding-status'
import { Route as OperationsCentreRouteImport } from './routes/operations-centre'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProviderReadyRouteImport } from './routes/provider-ready'
import { Route as ScenarioLabRouteImport } from './routes/scenario-lab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStatusRoute = OnboardingStatusRouteImport.update({
  id: '/onboarding-status',
  path: '/onboarding-status',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsCentreRoute = OperationsCentreRouteImport.update({
  id: '/operations-centre',
  path: '/operations-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderReadyRoute = ProviderReadyRouteImport.update({
  id: '/provider-ready',
  path: '/provider-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenarioLabRoute = ScenarioLabRouteImport.update({
  id: '/scenario-lab',
  path: '/scenario-lab',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRoute
  '/demo': typeof DemoRoute
  '/merchant': typeof MerchantRoute
  '/onboarding-status': typeof OnboardingStatusRoute
  '/operations-centre': typeof OperationsCentreRoute
  '/personal': typeof PersonalRoute
  '/products': typeof ProductsRoute
  '/provider-ready': typeof ProviderReadyRoute
  '/scenario-lab': typeof ScenarioLabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRoute
  '/demo': typeof DemoRoute
  '/merchant': typeof MerchantRoute
  '/onboarding-status': typeof OnboardingStatusRoute
  '/operations-centre': typeof OperationsCentreRoute
  '/personal': typeof PersonalRoute
  '/products': typeof ProductsRoute
  '/provider-ready': typeof ProviderReadyRoute
  '/scenario-lab': typeof ScenarioLabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRoute
  '/demo': typeof DemoRoute
  '/merchant': typeof MerchantRoute
  '/onboarding-status': typeof OnboardingStatusRoute
  '/operations-centre': typeof OperationsCentreRoute
  '/personal': typeof PersonalRoute
  '/products': typeof ProductsRoute
  '/provider-ready': typeof ProviderReadyRoute
  '/scenario-lab': typeof ScenarioLabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/demo'
    | '/merchant'
    | '/onboarding-status'
    | '/operations-centre'
    | '/personal'
    | '/products'
    | '/provider-ready'
    | '/scenario-lab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/business'
    | '/demo'
    | '/merchant'
    | '/onboarding-status'
    | '/operations-centre'
    | '/personal'
    | '/products'
    | '/provider-ready'
    | '/scenario-lab'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/demo'
    | '/merchant'
    | '/onboarding-status'
    | '/operations-centre'
    | '/personal'
    | '/products'
    | '/provider-ready'
    | '/scenario-lab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BusinessRoute: typeof BusinessRoute
  DemoRoute: typeof DemoRoute
  MerchantRoute: typeof MerchantRoute
  OnboardingStatusRoute: typeof OnboardingStatusRoute
  OperationsCentreRoute: typeof OperationsCentreRoute
  PersonalRoute: typeof PersonalRoute
  ProductsRoute: typeof ProductsRoute
  ProviderReadyRoute: typeof ProviderReadyRoute
  ScenarioLabRoute: typeof ScenarioLabRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-status': {
      id: '/onboarding-status'
      path: '/onboarding-status'
      fullPath: '/onboarding-status'
      preLoaderRoute: typeof OnboardingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations-centre': {
      id: '/operations-centre'
      path: '/operations-centre'
      fullPath: '/operations-centre'
      preLoaderRoute: typeof OperationsCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider-ready': {
      id: '/provider-ready'
      path: '/provider-ready'
      fullPath: '/provider-ready'
      preLoaderRoute: typeof ProviderReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenario-lab': {
      id: '/scenario-lab'
      path: '/scenario-lab'
      fullPath: '/scenario-lab'
      preLoaderRoute: typeof ScenarioLabRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BusinessRoute: BusinessRoute,
  DemoRoute: DemoRoute,
  MerchantRoute: MerchantRoute,
  OnboardingStatusRoute: OnboardingStatusRoute,
  OperationsCentreRoute: OperationsCentreRoute,
  PersonalRoute: PersonalRoute,
  ProductsRoute: ProductsRoute,
  ProviderReadyRoute: ProviderReadyRoute,
  ScenarioLabRoute: ScenarioLabRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
